all:
	@echo "Makefile.dist creates files from CVS, to prepare ./configure and other files"
	@echo "--> running aclocal ..."
	@aclocal
	@echo "--> running autoconf ..."
	@autoconf
	@echo "--> running automake ..."
	@automake
	@echo "--> cleaning few files ..."
	rm -rf config.cache
	perl admin/am_edit
	@rm -rf autom4te.cache
	@chmod +x ./configure
	@echo ""
	@echo "Now, you can run ./configure && make"
