.TH QTPARTED 1 "April, 2003"
.\" Please adjust this date whenever revising the manpage.
.SH NAME
QTParted \- A GUI for Parted
.SH SYNOPSIS
.B qtparted
.SH DESCRIPTION
.B qtparted 
is a GUI for parted looking (by design) like Powerquest Partition Magic.
While this is a work in progress and by far not complete, it is already
working nicely.

To use QTParted just start it using root privilege.
.PP
.SH OPTIONS
This program currently has no command line options
.SH AUTHOR
This manual page was written by Vanni Brutto <zanac@libero.it>
