.TH QTPARTED 1 "March, 2004"
.\" Please adjust this date whenever revising the manpage.
.SH NAME
QTParted \- A GUI for Parted
.SH SYNOPSIS
.B run_qtparted
.SH DESCRIPTION
.B run_qtparted
is a wrapper to run qtparted without X just in framebuffer mode.

.PP
.SH OPTIONS
This program currently has no command line options
.SH AUTHOR
This manual page was written by Fabian Franz <debian@fabian-franz.de> 
for the Debian project.
